#*******************How does Spring Boot connect to database?*************************
#Spring Boot auto-configures a DataSource using the properties defined in application.properties.
#Since you added PostgreSQL driver dependency, Spring Boot automatically detects and configures it.




spring.datasource.url= jdbc:postgresql://localhost:5432/usermanagement
spring.datasource.username=postgres
spring.datasource.password=root
# above lines tell how does connects your app to postgresql,databasename and port



spring.jpa.hibernate.ddl-auto=update
#ddl-auto=update,Automatically updates tables,Creates table if not exists,Updates schema if entity changes
spring.jpa.show-sql=true 
#Prints SQL queries in console.Used for debugging.
spring.jpa.properties.hibernate.format_sql=true
#Makes SQL readable in console.
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#Advanced Hibernate setting.Used for proper LOB (Large Object) handling in PostgreSQL


#Security/JWT
app.jwt.secret=change-this-super-secret-key-32+chars
#Secret key used to sign JWT,Used to verify token signature,If someone changes token payload:Signature becomes invalid.
#We sign the JWT using a secret key.When validating, we verify the signature using the same key.If signature doesn't match → token is rejected.
app.jwt.expiration-millis=86400000
#Used to:Set token expiration time,Prevent token misuse forever,JWT should always have expiration to reduce security risk.


#For Spring Security stateless REST
server.error.include-message=always

